import { db } from "@/db";
import { telegramConnections } from "@/db/schema";
import { eq } from "drizzle-orm";

const EXTERNAL_API_KEY = process.env.EXTERNAL_API_KEY;

/**
 * Shared auth guard for external API routes.
 *
 * Supports two authentication modes:
 *
 * 1. Global API key (server-to-server via Hermes Agent):
 *    Header: x-api-key = EXTERNAL_API_KEY (global shared secret)
 *    Header: x-chat-id = Telegram chat ID of the user
 *
 * 2. Per-user token (non-developer friendly):
 *    Header: x-api-key = Per-user token generated by Lamarin
 *    (no x-chat-id needed — the token itself identifies the user)
 *
 * Returns a Response on failure, or { userId } on success.
 */
export async function authenticateRequest(
  request: Request,
): Promise<{ userId: string } | Response> {
  const apiKey = request.headers.get("x-api-key");

  if (!apiKey) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), {
      status: 401,
      headers: { "Content-Type": "application/json" },
    });
  }

  // Mode 1: Global API key — requires x-chat-id to identify user
  if (apiKey === EXTERNAL_API_KEY) {
    const chatId = request.headers.get("x-chat-id");

    if (!chatId) {
      return new Response(
        JSON.stringify({
          error:
            "x-chat-id header is required when using global API key. Or use your personal Hermes token instead.",
        }),
        { status: 400, headers: { "Content-Type": "application/json" } },
      );
    }

    const [connection] = await db
      .select()
      .from(telegramConnections)
      .where(eq(telegramConnections.chatId, chatId));

    if (!connection || !connection.isActive) {
      return new Response(
        JSON.stringify({
          error: "User not found or Telegram not connected",
        }),
        { status: 404, headers: { "Content-Type": "application/json" } },
      );
    }

    return { userId: connection.userId };
  }

  // Mode 2: Per-user token — the token itself identifies the user
  const [connection] = await db
    .select()
    .from(telegramConnections)
    .where(eq(telegramConnections.hermesToken, apiKey));

  if (!connection || !connection.isActive) {
    return new Response(
      JSON.stringify({ error: "Invalid API key" }),
      { status: 401, headers: { "Content-Type": "application/json" } },
    );
  }

  return { userId: connection.userId };
}
